# Generated by Django 5.0.5 on 2024-05-14 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLTEIRO', 'solteiro'), ('CASAL', 'casal'), ('CONFORT', 'confort'), ('LUXO', 'luxo')], max_length=15)),
                ('disponibilidade', models.IntegerField(max_length=99)),
                ('valor', models.FloatField(max_length=9999)),
                ('descricao', models.TextField(max_length=300)),
                ('data_reserva', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
