# Generated by Django 5.0.5 on 2024-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_hotel_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='descricao',
        ),
        migrations.AddField(
            model_name='hotel',
            name='desc',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='foto_quarto',
            field=models.ImageField(default=0, upload_to='quartos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='titulo',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='descricao',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='disponibilidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tipo',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('CONFORT', 'Confort'), ('LUXO', 'Luxo')], max_length=15),
        ),
    ]
